# Generated by Django 5.0 on 2023-12-28 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='list',
            field=models.ForeignKey(default=2812, on_delete=django.db.models.deletion.CASCADE, to='Formulaire.fichier'),
            preserve_default=False,
        ),
    ]
