# Generated by Django 5.0 on 2023-12-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0002_person_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Personne',
        ),
    ]
